### ISSUE TITLE
Format option unexpected output

### ISSUE THREAD

**Issue by Krakn** [baskerville/xtitle#13]
Expected output:

     » xtitle -sf 'T%s'
    Tst
    TNew Issue · baskerville/xtitle - Chromium
    Tst
    TNew Issue · baskerville/xtitle - Chromium
    Tst
    ^C »

Actual output:

     » xtitle -sf 'T%s'
    TsTNTsTNTs^C »

A capitol "S" fixes half of the problem:

     » xtitle -sf 'T%S'
    TstTNew Issue · baskerville/xtitle - ChromiumTstTNew Issue · baskerville/xtitle - ChromiumTst^C »

Attempting to add a newline:

     » xtitle -sf 'T%S\n'
    Tst\nTNew Issue · baskerville/xtitle - Chromium\nTst\nTNew Issue · baskerville/xtitle - Chromium\nTst\n^C »

<code>printf</code>'s formatting specifiers are not interpreted as the README suggests. Am I doing this wrong, or is there something funky going on?

**Comment by 8carlosf** [comment]
well.. recent changes to xtitle made this..
solution: `echo -ne "T%ls\n" | xargs -0 xtitle -sf`
explanation: using `echo -ne` you can convert the 2 chars "\n" to a newline ('\n') send it via a pipe | and use xargs to convert the stdin into an argument. Also, now we use wchar_t in order to support UTF8 chars correctly, so `%s` is now `%ls`.

**Comment by baskerville** [comment]
More generally, it seems that there might be a [slight problem](https://en.wikipedia.org/wiki/Uncontrolled_format_string) with the current approach.

**Comment by 8carlosf** [comment]
Personally I don't think that security is a big concerne in this case.. because the user will provide a single format and can test it before doing so.. Also, exploiting that accidentally is almost impossible.
What would the alternative be? Also, recommend me a flag to make a mid truncate (leave T/2 chars in the beginning and T/2 in the end of the title if bigger than T) :)
